-- Insert initial heritage remedies
INSERT INTO public.heritage_remedies (
  title,
  description,
  ingredients,
  instructions,
  cooking_time,
  servings,
  health_benefits,
  remedy_explanation,
  precautions,
  region,
  tradition,
  illness,
  image_url,
  trust_score,
  votes
) VALUES
(
  'Turmeric Golden Milk',
  'A soothing, anti-inflammatory drink that has been used in Ayurvedic medicine for centuries',
  ARRAY['2 cups milk (dairy or plant-based)', '1 tsp turmeric powder', '1/2 tsp ground cinnamon', '1/4 tsp ground ginger', '1/4 tsp black pepper', '1 tbsp honey', 'Optional: 2-3 cardamom pods'],
  ARRAY['Heat milk in a small saucepan over medium heat', 'Add turmeric, cinnamon, ginger, and black pepper', 'Whisk continuously until warm but not boiling', 'Remove from heat and strain if using cardamom pods', 'Add honey to taste', 'Serve warm'],
  '10 minutes',
  '2 servings',
  ARRAY['Reduces inflammation', 'Boosts immune system', 'Aids digestion', 'Improves sleep quality', 'Natural pain relief'],
  'The combination of turmeric and black pepper increases curcumin absorption by 2000%. The warming spices help reduce inflammation and boost immunity.',
  ARRAY['Consult doctor if pregnant or nursing', 'May interact with blood-thinning medications', 'Start with small amounts if sensitive to spices'],
  'South Asia',
  'This golden milk recipe has been a staple in Ayurvedic medicine for over 4000 years. It is traditionally consumed before bedtime to promote healing and boost immunity.',
  'Common Cold, Inflammation',
  'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=2940',
  50,
  0
),
(
  'Ginger Honey Tea',
  'A warming remedy that helps with sore throat, cough, and nausea',
  ARRAY['2-inch piece fresh ginger', '2 cups water', '2 tbsp honey', '1 lemon', 'Optional: 2-3 peppercorns', 'Optional: 1 cinnamon stick'],
  ARRAY['Peel and thinly slice ginger', 'Boil water in a pot', 'Add ginger and optional spices', 'Simmer for 10 minutes', 'Strain into cups', 'Add honey and lemon juice to taste'],
  '15 minutes',
  '2 servings',
  ARRAY['Soothes sore throat', 'Reduces nausea', 'Anti-inflammatory', 'Boosts immune system', 'Aids digestion'],
  'Ginger contains gingerols and shogaols that have powerful anti-inflammatory and antioxidant properties. Honey adds antibacterial benefits.',
  ARRAY['Avoid if allergic to ginger', 'Reduce honey if diabetic', 'Consult doctor if on blood-thinning medication'],
  'East Asia',
  'This remedy has been used in Traditional Chinese Medicine for over 2500 years as a natural treatment for colds, flu, and digestive issues.',
  'Sore Throat, Nausea',
  'https://images.unsplash.com/photo-1608677087249-5c57c55aedef?auto=format&fit=crop&q=80&w=2940',
  50,
  0
),
(
  'Chamomile Lavender Sleep Tonic',
  'A calming herbal blend that promotes restful sleep and reduces anxiety',
  ARRAY['2 chamomile tea bags', '1 tbsp dried lavender', '2 cups hot water', '1 tsp honey', 'Optional: 1 slice lemon', 'Optional: 1 small piece valerian root'],
  ARRAY['Boil water and let cool slightly', 'Add chamomile tea bags and lavender', 'Steep for 5-7 minutes', 'Strain into cups', 'Add honey if desired', 'Drink 30 minutes before bedtime'],
  '10 minutes',
  '2 servings',
  ARRAY['Improves sleep quality', 'Reduces anxiety', 'Calms nervous system', 'Natural stress relief', 'Aids digestion'],
  'Chamomile contains apigenin, an antioxidant that binds to certain receptors in the brain that promote sleepiness. Lavender enhances the calming effects.',
  ARRAY['Avoid if allergic to ragweed', 'Not recommended during pregnancy', 'May cause drowsiness'],
  'Europe',
  'This sleep remedy combines traditional European herbal wisdom, where chamomile has been used as a natural sedative since ancient Roman times.',
  'Insomnia, Anxiety',
  'https://images.unsplash.com/photo-1573725342230-178c824a10f2?auto=format&fit=crop&q=80&w=2940',
  50,
  0
),
(
  'Apple Cider Vinegar Detox Drink',
  'A morning tonic that aids digestion and supports natural detoxification',
  ARRAY['2 tbsp apple cider vinegar (with mother)', '2 cups warm water', '1 tbsp honey', '1 lemon', '1/4 tsp cayenne pepper', 'Optional: 1/2 tsp cinnamon'],
  ARRAY['Warm water (not hot)', 'Add apple cider vinegar', 'Squeeze in fresh lemon juice', 'Add honey and spices', 'Stir well until honey dissolves', 'Drink first thing in morning'],
  '5 minutes',
  '2 servings',
  ARRAY['Supports digestion', 'Balances pH levels', 'Boosts metabolism', 'Aids detoxification', 'Improves skin health'],
  'The acetic acid in apple cider vinegar supports healthy blood sugar levels and aids in detoxification. The mother contains beneficial probiotics.',
  ARRAY['Start with small amounts', 'Dilute well to protect tooth enamel', 'Not recommended on empty stomach if sensitive'],
  'North America',
  'This remedy combines traditional folk medicine with modern wellness practices. Apple cider vinegar has been used as a health tonic since ancient times.',
  'Digestive Issues, Bloating',
  'https://images.unsplash.com/photo-1595614007536-6e6a8ef82139?auto=format&fit=crop&q=80&w=2940',
  50,
  0
),
(
  'Eucalyptus Steam Inhalation',
  'A respiratory clearing treatment using eucalyptus essential oil',
  ARRAY['5-10 drops eucalyptus essential oil', '4 cups boiling water', '1 large towel', 'Optional: 2-3 drops peppermint oil', 'Optional: 2-3 drops tea tree oil'],
  ARRAY['Boil water in a large pot', 'Remove from heat', 'Add essential oils', 'Place towel over head and pot', 'Inhale steam for 5-10 minutes', 'Repeat 2-3 times daily'],
  '15 minutes',
  '1 serving',
  ARRAY['Clears sinuses', 'Relieves congestion', 'Soothes respiratory tract', 'Anti-microbial benefits', 'Reduces inflammation'],
  'Eucalyptus oil contains eucalyptol, which has powerful decongestant and antimicrobial properties that help clear respiratory passages.',
  ARRAY['Keep eyes closed during treatment', 'Not for children under 7', 'Avoid if asthmatic without consultation', 'Keep face 12 inches from water'],
  'Australia',
  'This remedy originates from Aboriginal Australian medicine, where eucalyptus has been used for thousands of years to treat respiratory conditions.',
  'Congestion, Sinusitis',
  'https://images.unsplash.com/photo-1636634231142-9006194bc816?auto=format&fit=crop&q=80&w=2940',
  50,
  0
),
(
  'Elderberry Immune Syrup',
  'A traditional immune-boosting syrup made with elderberries and honey',
  ARRAY['1 cup dried elderberries', '4 cups water', '1 cup raw honey', '2 cinnamon sticks', '1 tbsp fresh ginger', '5 whole cloves'],
  ARRAY['Combine elderberries and water in pot', 'Add spices and bring to boil', 'Reduce heat and simmer 45 minutes', 'Strain and let cool to room temperature', 'Stir in honey', 'Store in airtight jar in refrigerator'],
  '1 hour',
  '16 servings',
  ARRAY['Boosts immune system', 'Antiviral properties', 'Rich in antioxidants', 'Reduces cold duration', 'Supports respiratory health'],
  'Elderberries are rich in anthocyanins and other compounds that boost immune function and have antiviral properties, particularly effective against flu viruses.',
  ARRAY['Not for children under 1 (honey)', 'Raw elderberries are toxic', 'Consult doctor if pregnant/nursing', 'May interact with immune medications'],
  'Europe',
  'Elderberry syrup has been used in European folk medicine since ancient times. Hippocrates called the elder tree his medicine chest.',
  'Cold and Flu Prevention',
  'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&q=80&w=2940',
  50,
  0
);